[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "ecb9bf36071ed1c7abab7b4b46171908862ebf67"
os = "macos"

    [[CGNS.download]]
    sha256 = "9b49991ec571aff40a698bbe014dff5abcb1c91ce0d660626438a087cb3fdd7d"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-apple-darwin.tar.gz"
[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "4a3999a3f9ff8e7e4bab9bf622ac5abad8d5095f"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "aeead23935021e7e5c989c010040827b8734252c7a47de714380bec00ba50b16"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-linux-gnu.tar.gz"
[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "bb5b39d1c7f3f5543c1b1645217d067cb77d0bbe"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "fddb9b4695f01b394573832edddc540f28c55398d44c1b7cc58e7c69df3eb3f1"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-linux-musl.tar.gz"
[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "691fe07d8d6def76162979525efb78003c0b7bd3"
os = "freebsd"

    [[CGNS.download]]
    sha256 = "7748939ae367ecc712373fcf4353d7d8bc07dc07f54f521f57cb0990841d5280"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-unknown-freebsd.tar.gz"
[[CGNS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e9eecb3bba9a4d5c7a9615e10ca5e0625b359a6c"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "5c3a2a4c5d2364d55c67e4a6f993a42184883e881e9e893ed63c588c8c84e59f"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv6l-linux-gnueabihf.tar.gz"
[[CGNS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11ad2baf29871539006f30d97eb8ed1eb8b1a504"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "8a70fc97258694a8e8672e0c0c1f7ac2b102cd0a91ca5e311f71d596c8dd7423"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv6l-linux-musleabihf.tar.gz"
[[CGNS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "679d303d761294cac09768f24a6fabbcd80f7774"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "ec079f29659e46e4c5c480309535ab4e46d9d8f54a301f6ee19ba26b307aa0ee"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv7l-linux-gnueabihf.tar.gz"
[[CGNS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0b0afd23e76f2fa4761f45227cd910a9cdecf84"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "177d8edbdf1d1b8bcdc1465049c17ec9092ca5823d02f2664a9816073cf42546"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv7l-linux-musleabihf.tar.gz"
[[CGNS]]
arch = "i686"
git-tree-sha1 = "818e5c30e88842304291895d15c94de739a0dc6d"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "488bf97194771eea5f12be42d31b09052cb814790dcf227c9fa6aa44803eef0a"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.i686-linux-gnu.tar.gz"
[[CGNS]]
arch = "i686"
git-tree-sha1 = "73317e921f018604e980fb46d0053a79a56eecb1"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "295eac1efbbea022f3976e13848e722c77722092a046219a48af371289d26c97"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.i686-linux-musl.tar.gz"
[[CGNS]]
arch = "i686"
git-tree-sha1 = "dd6529cf974731843ceaca33d7a91ded8cfe4aa4"
os = "windows"

    [[CGNS.download]]
    sha256 = "01fe5560fa9baa19ecefafb5a6898c60bd526e93ef6ed2bf428367da3a1308d1"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.i686-w64-mingw32.tar.gz"
[[CGNS]]
arch = "powerpc64le"
git-tree-sha1 = "a7ed7bcc6a72192c3d242da969ec158d1a43a260"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "e039150f48e49c66af9c2bcc4c431513bdac770c680af3042ad6d492fc4737dc"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.powerpc64le-linux-gnu.tar.gz"
[[CGNS]]
arch = "riscv64"
git-tree-sha1 = "846df9402dbe779d07f509fcd4bd90d51a71549d"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "24e11971ec2938e615d0159c17d5587826190bd6e8c76ae78dc3708564b5df2b"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.riscv64-linux-gnu.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "d5f8af3e30775ee05557103b4343cf74f6efab5b"
os = "macos"

    [[CGNS.download]]
    sha256 = "ae0dea6d52e4fa3d6b0008b6340c0811a3436eb0e8ffb20949979cc619b02f4a"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-apple-darwin.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "dee3761c634eee2f83ccfffaca0db767dc72c4b2"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "f98de910188e7edcc2e5b07a79c6f9e1258ee85791da0245b11c86955d20d713"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-linux-gnu.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "c5e9ee96a77febf3e81ba716d9a975b71dbd98e9"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "24d047b2d7ad0078e86aa96800aca20e7cecff3375b380004fde44d0f96f5c68"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-linux-musl.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "f357ea1554694f1f35ffcc340e7213c81d88dc65"
os = "freebsd"

    [[CGNS.download]]
    sha256 = "f440ef36d9913480261248de77d62ffaeb519e3dbba7d499a40293b8160552f5"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-unknown-freebsd.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "dd0c307b25eab706f98fd4165a2ebb08aa42fbc6"
os = "windows"

    [[CGNS.download]]
    sha256 = "b1d607a8f70828d91307a260014c45c9e487eb6f37b1818b418312629c7d2659"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-w64-mingw32.tar.gz"
