[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "00c04e2913abfc27d5b36fd9bd98f1506d76b2dc"
os = "macos"

    [[CGNS.download]]
    sha256 = "037470e59ae48e6054e10d14c120d46cdb0d3a09edb9a6dd4d795070a65a64e5"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-apple-darwin.tar.gz"
[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "548236a212e65ca87769042e88836c5dfba240ff"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "f49695d12f6707db945ee6ced17053bf5b2c9b88b3377f1fbd869734199223dd"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-linux-gnu.tar.gz"
[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "7bfa1a4ecf4ce3940c3fef56cfff7e22836da39e"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "5b8b988033a86c51feab5135831775206dc76fa21b059d26f8a7779dd2d4976c"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-linux-musl.tar.gz"
[[CGNS]]
arch = "aarch64"
git-tree-sha1 = "042563e243ed763b55d70e86e9b9bf1648980bd5"
os = "freebsd"

    [[CGNS.download]]
    sha256 = "56d10579737b3486d3ea5b0dd4e9e8e859ee4ce8a61b9f499194eeb61afa4d24"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.aarch64-unknown-freebsd.tar.gz"
[[CGNS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c81e5f4162b60bd7e8a8148f49d0efbed4b7ac2"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "ace79f970bd9da3b0e199de8e2e69cf4c8ee854a64814d12d009fa35a7d87690"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv6l-linux-gnueabihf.tar.gz"
[[CGNS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56749f5fa41ad439bca29e9c3bdcacf731ab7453"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "8285a258a216c50800112d4b8398c2491b041e5b62f173f4464a21330f5389e5"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv6l-linux-musleabihf.tar.gz"
[[CGNS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56a1f04c7767e85b712cb66ae37db80f57aa3689"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "2c46ac5c2eb9753f6f04feec5ec7f466898814ab61d51e717ef234e2ff4a2ba0"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv7l-linux-gnueabihf.tar.gz"
[[CGNS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "470d432522dbb36eb8fdf2a40fe53876ef9c13b1"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "92cd5491db4dfff253b6b0930d321de4a0285b1f70964367d065fef4e8e27920"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.armv7l-linux-musleabihf.tar.gz"
[[CGNS]]
arch = "i686"
git-tree-sha1 = "13f3245ba3ce3fe908413ba6dcbbe17468c42653"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "bfabc690fc668ef5bf52ff451d75fef3e78e67711f32636d35331998e7c48302"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.i686-linux-gnu.tar.gz"
[[CGNS]]
arch = "i686"
git-tree-sha1 = "3dac7316f051275386035d3964c96c0e19a1ec84"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "62e7f40c6884b69d788dcfaf51da5a3c600d2ce2239041fffa0798f3703adee6"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.i686-linux-musl.tar.gz"
[[CGNS]]
arch = "i686"
git-tree-sha1 = "84efd52ea2bd025888102fb94a034e9ac69a568c"
os = "windows"

    [[CGNS.download]]
    sha256 = "eebf35ace764e8587d0c034431cbcf7dfb0a71f495b97aa7f3402bc71caa4005"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.i686-w64-mingw32.tar.gz"
[[CGNS]]
arch = "powerpc64le"
git-tree-sha1 = "dcc3c68af5d9fc75da4e343469723c9784e311d0"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "3c510cb5b5020d90530f10149499143214d35189a1e73086b05c3bbe8ba4050b"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.powerpc64le-linux-gnu.tar.gz"
[[CGNS]]
arch = "riscv64"
git-tree-sha1 = "1707340a9b45eb293246ce64a40050b08c7e03f2"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "1044509bb47ccb109dd6c90ac9af209e91fde0e190d457e868964348514ce53a"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.riscv64-linux-gnu.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "07f2c3939ca7ee77a1cfbbcfd0adea8364433819"
os = "macos"

    [[CGNS.download]]
    sha256 = "2e14e71231de14f6d2e4b9c0a515986f52052b7515df2c220b6c27527e4bf54e"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-apple-darwin.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "83fd889299e7cc9e9670e9c150479fe3dcec0903"
libc = "glibc"
os = "linux"

    [[CGNS.download]]
    sha256 = "fe5666d850743f780677af5b8099cebf54464faa50157df8e74e4a3c6945dce7"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-linux-gnu.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "73e87a25120b20070d70e713f75bc6657b891414"
libc = "musl"
os = "linux"

    [[CGNS.download]]
    sha256 = "d14bcd0db5c4547e8b6826c0cd1e5c5c195ceb86d9ca8d484e9d68bc24e1b30b"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-linux-musl.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "26aece773458d2a2aae130d8e5508c6edd58b0c2"
os = "freebsd"

    [[CGNS.download]]
    sha256 = "3ea85c347b344f30ec5960693683b281c7c9ed21f8bb5c17db50138bcdfec675"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-unknown-freebsd.tar.gz"
[[CGNS]]
arch = "x86_64"
git-tree-sha1 = "234727faff555cf931d05c87b2b1560fb9a4b4a3"
os = "windows"

    [[CGNS.download]]
    sha256 = "721bedac5ca38e091c418dbfcea37adf74ed8f0c2e1c89f20c5a7abf5ac90633"
    url = "https://github.com/JuliaBinaryWrappers/CGNS_jll.jl/releases/download/CGNS-v4.5.1+0/CGNS.v4.5.1.x86_64-w64-mingw32.tar.gz"
