# Autogenerated wrapper script for CGNS_jll for x86_64-w64-mingw32
export cgnscheck, cgnscompress, cgnsconvert, cgnsdiff, cgnslist, cgnsnames, libcgns

using HDF5_jll
JLLWrappers.@generate_wrapper_header("CGNS")
JLLWrappers.@declare_library_product(libcgns, "libcgns.dll")
JLLWrappers.@declare_executable_product(cgnscheck)
JLLWrappers.@declare_executable_product(cgnscompress)
JLLWrappers.@declare_executable_product(cgnsconvert)
JLLWrappers.@declare_executable_product(cgnsdiff)
JLLWrappers.@declare_executable_product(cgnslist)
JLLWrappers.@declare_executable_product(cgnsnames)
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll)
    JLLWrappers.@init_library_product(
        libcgns,
        "bin\\libcgns.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cgnscheck,
        "bin\\cgnscheck.exe",
    )

    JLLWrappers.@init_executable_product(
        cgnscompress,
        "bin\\cgnscompress.exe",
    )

    JLLWrappers.@init_executable_product(
        cgnsconvert,
        "bin\\cgnsconvert.exe",
    )

    JLLWrappers.@init_executable_product(
        cgnsdiff,
        "bin\\cgnsdiff.exe",
    )

    JLLWrappers.@init_executable_product(
        cgnslist,
        "bin\\cgnslist.exe",
    )

    JLLWrappers.@init_executable_product(
        cgnsnames,
        "bin\\cgnsnames.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
